language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - chmod 0777 ./elder-brother
    - composer update --prefer-dist

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
